server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

hibernate:

polar:
  greeting: Welcome to the local book catalog!

spring:
  application:
    # The name of the application, used by the config server to filter the configuration
    name: catalog-service
  config:
    # Imports configuration data from a config server when available
    import: "optional:configserver:"
  cloud:
    config:
      # The URL of the configuration server
      uri: http://localhost:8888
      # Timeout on waiting to connect to the config server (ms)
      request-connect-timeout: 5000
      # Timeout on waiting to read configuration data from the config server (ms)
      request-read-timeout: 5000
      # Makes a failure to connect to the config server fatal
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: refresh

